services:

  ecu-service:
    build:
      context: ./docker/ecu-service
    container_name: ecu-service

    ports:
      - "8080:8080"


  rogue-app:
    build:
      context: ./docker/rogue-app
    container_name: rogue-app

    environment:
      TARGET_URL: http://ecu-service:8080/calculate
      LOAD_PROFILE: ${LOAD_PROFILE:-medium}
      LOAD_PROFILE_CONFIG: /app/config/load_profiles.yaml

    volumes:
      - ./config/load_profiles.yaml:/app/config/load_profiles.yaml:ro

    depends_on:
      - ecu-service
